export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const UPDATE_CART_QTY_OPTIMISTIC = 'UPDATE_CART_QTY_OPTIMISTIC';

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const CLEAR_CART_REQUEST = 'CLEAR_CART_REQUEST';
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';
export const CLEAR_CART_FAILURE = 'CLEAR_CART_FAILURE';

export const CHECKOUT_ORDER_REQUEST = 'CHECKOUT_ORDER_REQUEST';
export const CHECKOUT_ORDER_SUCCESS = 'CHECKOUT_ORDER_SUCCESS';
export const CHECKOUT_ORDER_FAILURE = 'CHECKOUT_ORDER_FAILURE';

// Section 11.2 Constants
export const CHECKOUT_INIT_REQUEST = 'CHECKOUT_INIT_REQUEST';
export const CHECKOUT_INIT_SUCCESS = 'CHECKOUT_INIT_SUCCESS';
export const CHECKOUT_INIT_FAILURE = 'CHECKOUT_INIT_FAILURE';

export const PLACE_ORDER_REQUEST = 'CHECKOUT_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'CHECKOUT_ORDER_SUCCESS';
export const PLACE_ORDER_FAILURE = 'CHECKOUT_ORDER_FAILURE';

export const CLEAR_CART = 'CLEAR_CART_SUCCESS';
